name: Automatisation des tests
on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installer les outils
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Compilation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Exécuter les tests CMake
        run: |
          cd build
          ctest --output-on-failure || true

  Tests_Fonctions:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Exécuter plusieurs tests individuellement
        run: |
          cd build
          echo "=== Test add ==="
          ./src/calculator add 10 5 || echo "Test add échoué"
          echo "=== Test sub ==="
          ./src/calculator sub 7 2 || echo "Test sub échoué"
          echo "=== Test mul ==="
          ./src/calculator mul 3 4 || echo "Test mul échoué"
          echo "=== Test div ==="
          ./src/calculator div 8 2 || echo "Test div échoué"
          echo "=== Test car ==="
          ./src/calculator car 16 || echo "Test car échoué"